name = "Yames SP"
author = "hexagonelle"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46bcfa66041653ac7f5e3831aae0585ee7599d47f29fc5531cef6251323cc498"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = "1.20"
datapack-folder = "config\\paxi\\datapacks"
no-internal-hashes = true
