name = "Yames SP"
author = "hexagonelle"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b4b7f6c6825e4d7ca0c098e6c1774b0a9f636bfb9c2e92e6875bc557e98aeff"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = "1.20"
datapack-folder = "config\\paxi\\datapacks"
no-internal-hashes = true
